function runTestFile(mdlname)
% Copyright 2021 The MathWorks, Inc.
tests = modelTestsAction('ModelName', mdlname,...
    'TestFile', ['Test_', mdlname, '.mldatx'],...
    'PDFReport', 'yes',...
    'JUnitFormatResults', 'yes'); 
tests.runTestsAndGenerateResults();